defaults: &defaults
  localization:
    directory: lib/locales/
    default_locale: ru

development:
  <<: *defaults

test:
  <<: *defaults
  localization:
    default_locale: en

production:
  <<: *defaults