defaults: &defaults
  localization:
    directory: lib/locales/
    default: ru
  widgets:
    def_limit: 10

development:
  <<: *defaults

test:
  <<: *defaults
  localization:
    default_locale: en

production:
  <<: *defaults