defaults: &defaults
  localization:
    directory: lib/locales/
    default: ru
  offset_default: 0
  limit_default: 10
  limit_preview: 6
  widgets:
    level_default: city
    limit_default: 10
  images:
    dir: /opt/galaxias/bublik/webapps/images/
    preview_size: 300

development:
  <<: *defaults

test:
  <<: *defaults
  images:
    dir: <%= "#{Rails.root}/public/images/" %>
    preview_size: 300

production:
  <<: *defaults