defaults: &defaults
  localization:
    directory: lib/locales/
    default: ru
  offset_default: 0
    widgets:
      level_default: city
      limit_default: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults